services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "FelineX"
      POSTGRES_PASSWORD: "FelineXServerPassword"
      POSTGRES_DB: FelineX
    restart: unless-stopped
    ports:
      - "5433:5432"
  
  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: Web/Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db
  