// <auto-generated />
using System;
using APIServer.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240411092729_RemoveListTests")]
    partial class RemoveListTests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Shared.DB.Classes.Test.Task.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("InteractionType")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid?>("TestId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("User")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.HasIndex("User");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Shared.DB.Classes.Test.Task.TaskAnswer.TaskAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AnsweredTaskId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TestAnswerId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AnsweredTaskId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TestAnswerId");

                    b.ToTable("TaskAnswers");
                });

            modelBuilder.Entity("Shared.DB.Classes.Test.Task.TaskAnswer.TestAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AnsweredTestId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AnsweredTestId");

                    b.HasIndex("StudentId");

                    b.ToTable("TestAnswers");
                });

            modelBuilder.Entity("Shared.DB.Classes.Test.Task.ThemeTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Theme")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ThemeTasks");
                });

            modelBuilder.Entity("Shared.DB.Classes.Test.Task.VariableAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("StringAnswer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TaskAnswerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TaskAnswerId1")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TaskAnswerId");

                    b.HasIndex("TaskAnswerId1");

                    b.HasIndex("TaskId");

                    b.ToTable("VariableAnswers");
                });

            modelBuilder.Entity("Shared.DB.Classes.Test.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TestName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("Shared.DB.Classes.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<uint>("AccessFlags")
                        .HasColumnType("int unsigned");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shared.DB.Classes.User.UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("GroupCreatorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("GroupCreatorId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("TaskThemeTask", b =>
                {
                    b.Property<Guid>("ThematicsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ThemeTask")
                        .HasColumnType("char(36)");

                    b.HasKey("ThematicsId", "ThemeTask");

                    b.HasIndex("ThemeTask");

                    b.ToTable("TaskThemeTask");
                });

            modelBuilder.Entity("UserUserGroup", b =>
                {
                    b.Property<Guid>("StudentsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserGroupsId")
                        .HasColumnType("char(36)");

                    b.HasKey("StudentsId", "UserGroupsId");

                    b.HasIndex("UserGroupsId");

                    b.ToTable("UserUserGroup");
                });

            modelBuilder.Entity("Shared.DB.Classes.Test.Task.Task", b =>
                {
                    b.HasOne("Shared.DB.Classes.Test.Test", null)
                        .WithMany("Tasks")
                        .HasForeignKey("TestId");

                    b.HasOne("Shared.DB.Classes.User.User", "Creator")
                        .WithMany()
                        .HasForeignKey("User");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Shared.DB.Classes.Test.Task.TaskAnswer.TaskAnswer", b =>
                {
                    b.HasOne("Shared.DB.Classes.Test.Task.Task", "AnsweredTask")
                        .WithMany()
                        .HasForeignKey("AnsweredTaskId");

                    b.HasOne("Shared.DB.Classes.User.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.HasOne("Shared.DB.Classes.Test.Task.TaskAnswer.TestAnswer", null)
                        .WithMany("TaskAnswers")
                        .HasForeignKey("TestAnswerId");

                    b.Navigation("AnsweredTask");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Shared.DB.Classes.Test.Task.TaskAnswer.TestAnswer", b =>
                {
                    b.HasOne("Shared.DB.Classes.Test.Test", "AnsweredTest")
                        .WithMany()
                        .HasForeignKey("AnsweredTestId");

                    b.HasOne("Shared.DB.Classes.User.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.Navigation("AnsweredTest");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Shared.DB.Classes.Test.Task.VariableAnswer", b =>
                {
                    b.HasOne("Shared.DB.Classes.Test.Task.TaskAnswer.TaskAnswer", null)
                        .WithMany("GotVariables")
                        .HasForeignKey("TaskAnswerId");

                    b.HasOne("Shared.DB.Classes.Test.Task.TaskAnswer.TaskAnswer", null)
                        .WithMany("MarkedVariables")
                        .HasForeignKey("TaskAnswerId1");

                    b.HasOne("Shared.DB.Classes.Test.Task.Task", "Task")
                        .WithMany("VariableAnswers")
                        .HasForeignKey("TaskId");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Shared.DB.Classes.Test.Test", b =>
                {
                    b.HasOne("Shared.DB.Classes.User.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Shared.DB.Classes.User.UserGroup", b =>
                {
                    b.HasOne("Shared.DB.Classes.User.User", "GroupCreator")
                        .WithMany()
                        .HasForeignKey("GroupCreatorId");

                    b.Navigation("GroupCreator");
                });

            modelBuilder.Entity("TaskThemeTask", b =>
                {
                    b.HasOne("Shared.DB.Classes.Test.Task.ThemeTask", null)
                        .WithMany()
                        .HasForeignKey("ThematicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.DB.Classes.Test.Task.Task", null)
                        .WithMany()
                        .HasForeignKey("ThemeTask")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserUserGroup", b =>
                {
                    b.HasOne("Shared.DB.Classes.User.User", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.DB.Classes.User.UserGroup", null)
                        .WithMany()
                        .HasForeignKey("UserGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.DB.Classes.Test.Task.Task", b =>
                {
                    b.Navigation("VariableAnswers");
                });

            modelBuilder.Entity("Shared.DB.Classes.Test.Task.TaskAnswer.TaskAnswer", b =>
                {
                    b.Navigation("GotVariables");

                    b.Navigation("MarkedVariables");
                });

            modelBuilder.Entity("Shared.DB.Classes.Test.Task.TaskAnswer.TestAnswer", b =>
                {
                    b.Navigation("TaskAnswers");
                });

            modelBuilder.Entity("Shared.DB.Classes.Test.Test", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
